// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrgwqknklmkjupmkbkae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyZ3dxa25rbG1ranVwbWtia2FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjE3NTQsImV4cCI6MjA2NTQ5Nzc1NH0.inEKnU2b4KJB_TTN45iZhOeISNx66vgh8DnGkAaXWk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);